# Business Problem - Predict the price of bangalore house

### using SUPPORT VECTOR REGRESION - Supervised ML Algorithm

In [2]:
import pandas as pd

In [6]:
#Loading Datasets >> Data is already cleaned/preprocessed

df = pd.read_csv(r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB")
df.head()                 

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [7]:
X = df.drop('price',axis=1)
y = df['price']

print('shape of X = ', X.shape)
print('shape of y = ', y.shape)

shape of X =  (7120, 107)
shape of y =  (7120,)


In [10]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.1 , random_state = 23)

print('shape of X_train = ',  X_train.shape)
print('shape of X_test = ',  X_test.shape)
print('shape of y_train = ',  y_train.shape)
print('shape of y_test = ',  y_test.shape)

shape of X_train =  (6408, 107)
shape of X_test =  (712, 107)
shape of y_train =  (6408,)
shape of y_test =  (712,)


In [11]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

#### Support Vector Regression - ML Model Training

In [12]:
#ML Model Training

from sklearn.svm import SVR


In [13]:
svr_rbf = SVR(kernel = 'rbf')
svr_rbf.fit(X_train , y_train)
svr_rbf.score(X_test , y_test)


0.3125361628688551

In [14]:
svr_lin = SVR(kernel = 'linear')
svr_lin.fit(X_train , y_train)
svr_lin.score(X_test , y_test)


0.7937333269006605

In [15]:
svr_poly= SVR(kernel = 'poly' , degree=2)
svr_poly.fit(X_train , y_train)
svr_poly.score(X_test , y_test)

0.10592072334006886

Now looking at the above results we see that the linear regression suits best to our model and the rest are non efficient.

In [18]:
X_test[0]

array([-0.44731973,  0.55436337, -0.1880882 , -0.55235685, -0.55935328,
        0.57783079, -0.47212367, -0.25940022,  0.51711223, -0.18316219,
       -0.16358035, -0.15269327, -0.12781331, -0.13031282, -0.12969216,
       -0.12397576, -0.12267157, -0.11867817, -0.11867817, -0.11385244,
       -0.11243765, -0.1088243 , -0.11100574, -0.11028316, -0.09218776,
       -0.08956926, -0.08956926, -0.08867981, -0.08687445, -0.08409599,
       -0.08314981, -0.0812253 , -0.08314981, -0.08024621, -0.07925533,
       -0.07925533, -0.07410748, -0.07620739, -0.07825222, -0.07084363,
       -0.07410748, -0.07620739, -0.07194769, -0.0685833 , -0.07410748,
       -0.0751646 , -0.0730354 , -0.07194769, -0.07410748, -0.07194769,
       -0.06624738, -0.06972245, -0.06624738, -0.06624738, -0.07084363,
       -0.06624738, -0.06972245, -0.06624738, -0.06504853, -0.06258317,
       -0.06504853, -0.06131393, -0.06504853, -0.06258317, -0.06001827,
       -0.06001827, -0.06382756, -0.06258317, -0.06258317, -0.06

In [17]:
#Home Price Prediction

svr_lin.predict([X_test[0]])

array([61.3650976])

In [20]:
y_pred = svr_lin.predict(X_test)
y_pred

array([ 61.3650976 ,  87.16166188, 215.34234796,  45.63633263,
        71.41799929,  50.89239641,  47.91008519,  67.75714   ,
        50.34082095,  66.41811733,  26.22806895,  72.20895589,
        28.80295815,  39.45262317,  90.90543873,  73.32546411,
       294.48916675, 193.67545539,  61.10817329, 124.29292439,
        81.45575519, 133.74917143,  50.25002109, 228.4665403 ,
       165.58861131, 104.88282251,  33.61403623,  54.50273752,
        45.1176789 , 117.57399551,  38.77407461, 138.75212787,
        98.24206702,  92.35137868,  37.00589499,  92.17965049,
        44.79322629, 109.32876917,  66.66543066,  67.94041413,
        42.49167584,  47.89395477,  55.15413706,  48.02661734,
       106.97502555, 421.15906616, 129.94262108, 177.75213771,
        51.85635961,   3.87008644, 225.31235274, 117.24123236,
        41.72970308,  96.11421644, 132.08456825,  61.11965935,
        36.5106263 ,  58.99519013,  75.1086705 ,  41.39050566,
       100.60385509, 837.84735703, 117.10015289,  61.50

In [34]:
y_test

4579     59.0
6860     88.0
5141    218.0
5100     47.0
5182     68.0
        ...  
2230    180.0
6261     50.4
2919     56.0
1748     44.0
6381     45.0
Name: price, Length: 712, dtype: float64

In [36]:
#rms and rmse

from sklearn.metrics import mean_squared_error
import numpy as np

mse= mean_squared_error(y_test , y_pred)
rmse = np.sqrt(mse)

print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  2882.49495649361
RMSE =  53.68887181244927
