# Business Problem  - Predict the Price of House

## Using Linear Regression - Supervised ML Algorithm

In [1]:
#Load Libraries

import pandas as pd

In [2]:
#The data is already pre processed - This is just because to save time and explain the algorithm

df = pd.read_csv(r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB")
df

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                             0                    0   
4

In [3]:
#Here 'Price'  is Y and rest are X

#### Data Split

In [4]:
x = df.drop('price',axis=1)
y = df['price']

print('Shape of x = ', x.shape)
print('Shape of y = ', y.shape)

Shape of x =  (7120, 107)
Shape of y =  (7120,)


In [5]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=51)
print('Shape of x_train = ' ,x_train.shape)
print('Shape of x_test = ' ,x_test.shape)
print('Shape of y_train = ' ,y_train.shape)
print('Shape of y_test = ' ,y_test.shape)

Shape of x_train =  (5696, 107)
Shape of x_test =  (1424, 107)
Shape of y_train =  (5696,)
Shape of y_test =  (1424,)


####  Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)

x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)

### Linear Regression - Training ML Model

In [7]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()


lr.fit(x_train , y_train)

LinearRegression()

In [8]:
lr.coef_

array([-6.59024772e+00, -1.62930761e+00,  1.06720828e-01, -1.75095448e+01,
        2.28582625e-02,  4.36069968e-01, -4.46757919e+00, -1.88837277e+01,
       -5.49922231e+00, -2.41364386e+01, -1.53245663e+01,  3.74668000e+00,
       -8.09235897e+00,  1.13490633e+01, -5.03976356e-01, -1.23572003e+01,
       -1.68308265e+00,  1.77330608e+01, -1.25601096e+01,  1.71287398e+01,
       -2.86131166e+01, -1.18849446e+01, -9.61713976e+00,  1.24353962e-01,
        1.19527714e+01,  1.47859679e+01, -3.98055629e+01, -1.35637890e+01,
       -5.82991815e+00,  1.63458962e+01, -6.35491384e+00, -1.03981802e+00,
        8.41322652e+00, -1.84268729e+01, -2.60577521e-01, -1.96325111e+01,
        5.72076283e+00,  1.01383131e+01,  4.20368413e+01,  5.17016815e-02,
        1.55824293e+00,  3.59890859e+00, -4.45286367e+00,  1.35163575e+01,
       -1.86840951e+01, -3.97372661e+01,  1.57105165e+00, -1.00300983e+00,
       -1.16949201e+01, -1.69999860e+01, -1.24341533e+01,  3.78277813e+00,
        1.25817509e+01, -

In [9]:
lr.intercept_

-127.23946860110607

### Predict the value of Home and Test

In [10]:
x_test.iloc[0, :]

bath                              3.000000
balcony                           1.584376
total_sqft_int                 1700.000000
bhk                               3.000000
price_per_sqft                 4705.882353
                                  ...     
location_Hosur Road               0.000000
location_Horamavu Banaswadi       0.000000
location_Domlur                   0.000000
location_Mahadevpura              0.000000
location_Tumkur Road              0.000000
Name: 2435, Length: 107, dtype: float64

In [11]:
lr.predict([x_test.iloc[0,:]])

array([76.90661876])

In [12]:
lr.predict(x_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [13]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [14]:
lr.score(x_test, y_test) *100  #In %

79.03837092681417

# Lasso and Ridge Regression

In [25]:
from sklearn.linear_model import Ridge,Lasso

In [26]:
rd = Ridge()


rd.fit(x_train , y_train)

rd.score(x_test , y_test)

0.7902567335386035

###### Now, We can see that the the previous accuracy is little lower than this one. So, This is how it helps when the data is very big

In [27]:
ls = Lasso()


ls.fit(x_train , y_train)

ls.score(x_test , y_test)

0.7944621580348218

In [28]:
#Playing with alpha


rd2 = Ridge(alpha = 2)


rd2.fit(x_train , y_train)

rd2.score(x_test , y_test)

0.7901224185854403

In [29]:
ls2 = Lasso(alpha = 2)


ls2.fit(x_train , y_train)

ls2.score(x_test , y_test)

0.803612738923202

In [35]:
ls2 = Lasso(alpha = 3)


ls2.fit(x_train , y_train)

ls2.score(x_test , y_test)

0.8116146399804799

## Model Evaluation - Important Specs   RMS & RMSE

### Root Mean Square Error

In [36]:
y_pred = lr.predict(x_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [38]:
y_test  #There is good amount of difference in the predicted and actual values.

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [44]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [45]:
mse = mean_squared_error(y_test , y_pred)
rmse = np.sqrt(mse)

print('MSE = ' , mse)
print('RMSE = ' , rmse)

MSE =  4211.806905825007
RMSE =  64.898435311069


### R squared

In [46]:
from sklearn.metrics import r2_score

In [48]:
r2s = r2_score(y_test , y_pred)
r2s

0.7903837092681417